.github/workflows/ci.yml
Cargo.toml
src/hash/rpo/digest.rs
src/lib.rs
src/merkle/merkle_path_set.rs
src/merkle/merkle_tree.rs
src/merkle/mod.rs

feat: add no-std support

---

Cargo.toml
benches/hash.rs

feat: benchmark RPO

---

src/hash/rpo/digest.rs

Implement ord for rpo

---

README.md
src/hash/rpo/mod.rs

This PR updates the main README file with info about what the crypto crate currently contains.

Update README file in preparation for v0.1 release

---

.github/workflows/ci.yml
Cargo.toml
README.md
benches/hash.rs
src/hash/blake/mod.rs
src/hash/blake/tests.rs
src/hash/mod.rs
src/hash/rpo/digest.rs
src/hash/rpo/mds_freq.rs
src/hash/rpo/mod.rs
src/hash/rpo/tests.rs
src/lib.rs
src/merkle/merkle_path_set.rs
src/merkle/merkle_tree.rs
src/merkle/mod.rs

This PR tracks progress of v0.1 release of crypto crate.

Tracking PR for v0.1 release

---

benches/hash.rs

This PR addresses #14 , as part of #12 , and implements benchmarks for Blake3 hash function.

feat: blake3 benchmarks

---

README.md
benches/README.md

The following addresses #15 . The references that are included should be double checked for correct correspondence with the cited implementation.

Benchmark instructions for hash functions

---

README.md
benches/README.md

This PR updates some wording and benchmark tables in README files.

Minor updates to main and benchmark README files

---

CHANGELOG.md
Cargo.toml
README.md

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

chore: prepare for `v0.1.2` release

---

CHANGELOG.md
Cargo.toml
README.md
src/hash/rpo/mod.rs
src/hash/rpo/tests.rs
src/lib.rs
src/merkle/index.rs
src/merkle/merkle_path_set.rs
src/merkle/merkle_tree.rs
src/merkle/mod.rs
src/merkle/path.rs
src/merkle/path_set.rs
src/merkle/simple_smt/mod.rs
src/merkle/simple_smt/tests.rs

This PR is for preparing v0.1.2 release.

v0.1.2 release

---

CHANGELOG.md
Cargo.toml
src/hash/blake/mod.rs
src/hash/mod.rs
src/hash/rpo/mod.rs
src/lib.rs

This release just re-exports a few additional elements from `winter-crpto` and should not contain any breaking changes.

v0.1.4 release

---

src/bit.rs
src/hash/rpo/digest.rs
src/lib.rs
src/merkle/index.rs
src/merkle/merkle_tree.rs
src/merkle/mod.rs
src/merkle/simple_smt/mod.rs
src/merkle/store.rs

fix: #89
This adds a Merkle Store implementation.

Add merkle store

---

src/merkle/store.rs

This commit introduce common derive proc macros to MerkleStore. These are required downstream as the in-memory storage can be cloned.
It also introduces constructors common to the other types of the crate that will help to build a merkle store, using a build pattern.

refactor: add derive proc macros to merkle store

---

.git-blame-ignore-revs

the pre-commit PR has been merged, this adds the commit that ran pre-commit and formated the code base into the [`.git-blame-ignore-revs`](https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file)

ignore pre commit rev

---

src/merkle/merkle_tree.rs

the path does not include the root

chore: clarified assert message

---

src/lib.rs
src/merkle/merkle_tree.rs
src/merkle/mod.rs
src/utils.rs

Formatted result looks like this:
```
880abe452320966617646e7740b014954300f19a28780a0889d62ff33f4b0534
1ade1369091efa31201e9b60c9c28874d0ddce5362b335135a6bb4c917285983
3e60a9c843b4bb19f7a0572102e6507195f5240767a396335fd21981b048b807
0100000000000000000000000000000000000000000000000000000000000000
0200000000000000000000000000000000000000000000000000000000000000
0300000000000000000000000000000000000000000000000000000000000000
0400000000000000000000000000000000000000000000000000000000000000
```
and
```
[0400000000000000000000000000000000000000000000000000000000000000, 1ade1369091efa31201e9b60c9c28874d0ddce5362b335135a6bb4c917285983]
```
I added this to make it easier for me to visualize the data while debugging
- …

Format merkle tree

---

src/merkle/store/mod.rs
src/merkle/store/tests.rs

Added with_merkle_paths constructor, this should be useful for @Al-Kindi-0 when using the store with the proving code.
And unit tests for each constructor type.

store: added with_merkle_paths constructor

---

src/merkle/store/mod.rs

This adds some hopefully useful documentation to the store.
rendered:

Store docs

---

src/merkle/store/mod.rs
src/merkle/store/tests.rs

As the title says. Merge/Review after https://github.com/0xPolygonMiden/crypto/pull/108

Add serde to merklestore

---

CHANGELOG.md
Cargo.toml
LICENSE
README.md
src/hash/blake/mod.rs
src/hash/rpo/mod.rs

This PR prepares v0.2 release. Specifically:
* Updates create versions, README, and CHANGELOG.
* Updates Winterfell dependencies to v0.6.0.

Prepare v0.2 release

---

src/merkle/mmr/accumulator.rs
src/merkle/mmr/full.rs
src/merkle/mmr/tests.rs

based on https://github.com/0xPolygonMiden/crypto/pull/126#issuecomment-1499282439

mmr: optimized peak hash for Miden VM

---

src/merkle/store/mod.rs

feat: add .inner_nodes() to [MerkleStore]

---

src/merkle/mmr/accumulator.rs
src/merkle/mmr/mod.rs

This PR refactors the `MmrPeaks` interface to decouple padding and hashing peaks.  We publicly expose the method for padding peak such that downstream consumers can leverage it. 

refactor: Mmr accumulator

---

src/merkle/simple_smt/mod.rs
src/merkle/tiered_smt/mod.rs

Add `EMPTY_VALUE` associated constant to SMTs

---

src/merkle/index.rs
src/merkle/partial_mt/mod.rs
src/merkle/partial_mt/tests.rs
src/merkle/store/mod.rs
src/utils/mod.rs

This PR adds implementation of the `inner_nodes` function and serialization for the `PartialMerkleTree` struct.

Enhancement of the Partial Merkle Tree

---

src/merkle/tiered_smt/proof.rs

Adds basic traits Debug/PartialEq/Eq to the TSMT, and methods to split into parts, and construct from parts.
The former are useful for coding. The later I need to encode/decode the data into/from protobuf.

TSMT proof basic traits

---

src/merkle/tiered_smt/error.rs
src/merkle/tiered_smt/mod.rs
src/merkle/tiered_smt/proof.rs

This is useful for client applications that are parsing data from the network.

tsmt: return error code instead of panic

---

src/merkle/mod.rs

the tsmt module is not public, so the error has to be re-exported (otherwise one can not wrap it)

tsmt: export smt error

---

src/merkle/tiered_smt/error.rs
src/merkle/tiered_smt/mod.rs
src/merkle/tiered_smt/nodes.rs
src/merkle/tiered_smt/proof.rs
src/merkle/tiered_smt/tests.rs

This PR fixes the bug described in https://github.com/0xPolygonMiden/crypto/pull/173#discussion_r1282962782.

Bug fix in TSMT for depth 64 removal

---

src/merkle/error.rs
src/merkle/mod.rs

small code reorg to make `mod.rs` smaller

error: moved to its own module

---

src/merkle/store/mod.rs

This PR modifies the logic of the `MerkleStore::non_empty_leaves(..)` method to support extraction of leaves in a TSMT where the leaves are not necessarily positioned at the trees max depth.  The way this works is that if we encounter a leaf node above the max depth for which we do not have a corresponding entry in the `nodes` map then we assume it is a leaf.

modify MerkleStore::non_empty_leaves to support TSMT

---

.github/workflows/ci.yml
.gitmodules
Cargo.toml
build.rs
rustfmt.toml
src/dsa/mod.rs
src/dsa/rpo_falcon512/error.rs
src/dsa/rpo_falcon512/falcon_c/api_rpo.h
src/dsa/rpo_falcon512/falcon_c/falcon_rpo.c
src/dsa/rpo_falcon512/falcon_c/rpo.c
src/dsa/rpo_falcon512/falcon_c/rpo.h
src/dsa/rpo_falcon512/ffi.rs
src/dsa/rpo_falcon512/keys.rs
src/dsa/rpo_falcon512/mod.rs
src/dsa/rpo_falcon512/polynomial.rs
src/dsa/rpo_falcon512/signature.rs
src/lib.rs
src/merkle/merkle_tree.rs
src/merkle/mmr/full.rs
src/merkle/mmr/tests.rs
src/merkle/partial_mt/mod.rs
src/merkle/path.rs
src/merkle/simple_smt/mod.rs
src/merkle/simple_smt/tests.rs
src/merkle/store/mod.rs
src/merkle/tiered_smt/values.rs
src/utils/mod.rs

This PR proposes an adaptation of the reference C implementation so that it uses RPO instead of SHAKE256 for the hash-to-point algorithm. This PR supersedes #169 and uses the `PQClean` repository as a sub-module.

Falcon DSA

---

src/hash/rpo/digest.rs

Additional conversions to/from the rpo digest

rpo: added conversions for digest

---

src/merkle/mod.rs

mmr: publicly export MmrDelta

---

src/merkle/mmr/full.rs
src/merkle/mmr/tests.rs

The previous implementation of the `Mmr` only created diffs from an old version against the version of the structure. This changes the existing method so that a user can request updates for two arbitrary versions.
This is necessary to implement the state sync endpoint, which doesn't necessarily return the `MmrDelta` for the latest version of the `Mmr`

mmr: support arbitrary from/to delta updates

---

Cargo.toml

Bump winterfell release to .7

---

src/merkle/mmr/full.rs
src/merkle/mmr/tests.rs

Extends the `Mmr.accumulator` method, so that it is possible to return the peaks for an older version of the `Mmr`. This is useful for the node's store.

mmr: support accumulator of older forest versions

---

src/merkle/empty_roots.rs
src/merkle/simple_smt/mod.rs

The previous version unnecessarily copied the static data.

simple_smt: reduce serialized size, use static hashes of the empty word

---

src/merkle/path.rs

serde: for MerklePath, ValuePath, and RootPath

---

src/rand/mod.rs
src/rand/rpo.rs

This PR adds serialization to `RpoRandomCoin` struct and also cleans up a few minor things related to the new `rand` module.

feat: add serialization to `RpoRandomCoin`

---

src/rand/mod.rs

This is needed to remove the dependency of Miden VM on Winter-crypto.

Export default randomcoin

---

.github/workflows/ci.yml
src/dsa/rpo_falcon512/mod.rs
src/dsa/rpo_falcon512/polynomial.rs
src/dsa/rpo_falcon512/signature.rs
src/merkle/delta.rs
src/merkle/mmr/delta.rs
src/merkle/path.rs
src/rand/rpo.rs

This fixes some syntax issues in the existing documentation and add a CI check for it.

Fix doc syntax

---

src/merkle/smt/full/mod.rs
src/merkle/store/mod.rs

Add methods to `Smt` necessary for VM tests

---

src/merkle/smt/full/proof.rs

Adds accessors to fields in `SmtProof`

`SmtProof`: add accessors

---

Cargo.toml
src/dsa/rpo_falcon512/keys/mod.rs
src/dsa/rpo_falcon512/keys/secret_key.rs
src/dsa/rpo_falcon512/math/polynomial.rs
src/dsa/rpo_falcon512/mod.rs
src/dsa/rpo_falcon512/signature.rs

Also changes the `Rng` used in the tests.

Fixes a few issues for migrating Miden VM 

---

src/merkle/smt/full/mod.rs

Adding serialization and deserialization to the SMT. I need that in `miden-base` for `StorageMaps`.

feature: adding serialization to the SMT

---

src/rand/mod.rs
src/rand/rpx.rs

This PR adds random coin implementation for RPX. 
This is needed for the new `miden-gpu` crate integration to `miden-vm` which adds gpu accelaration using RPX.

Add RPX random coin

---

src/hash/mod.rs
src/hash/rescue/mod.rs
src/hash/rescue/rpo/mod.rs
src/hash/rescue/rpx/mod.rs

ref: https://github.com/0xPolygonMiden/crypto/pull/311#discussion_r1591871430

Export rpx error

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/hash/blake/mod.rs
src/hash/rescue/rpo/digest.rs
src/hash/rescue/rpo/mod.rs
src/hash/rescue/rpx/digest.rs
src/hash/rescue/rpx/mod.rs

Migrate to Winterfell release

---

CHANGELOG.md
Cargo.lock
Cargo.toml
Makefile
config.toml
fuzz/Cargo.toml
src/dsa/rpo_falcon512/keys/secret_key.rs
src/dsa/rpo_falcon512/math/samplerz.rs
src/main.rs
src/merkle/smt/full/concurrent/tests.rs
src/rand/rpo.rs
src/rand/rpx.rs

Updates the `rand` dependency to the `0.9` version
Related to: https://github.com/0xPolygonMiden/miden-node/issues/729

chore: update `rand` dependency

---

CHANGELOG.md
miden-crypto/src/dsa/rpo_falcon512/keys/public_key.rs
miden-crypto/src/dsa/rpo_falcon512/math/polynomial.rs
miden-crypto/src/dsa/rpo_falcon512/signature.rs
miden-crypto/src/hash/mod.rs
miden-crypto/src/hash/rescue/rpo/digest.rs

This PR resolves documentation lints (`missing_docs`) triggered by `#![deny(missing_docs)]`.
Relation to #255
This PR partially addresses #255. As discussed in https://github.com/0xMiden/crypto/pull/407#issuecomment-2848876215 , incremental PRs covering different modules/files are acceptable.
This is approximately 1/3 to 1/4 of the total work required for #255. Future PRs will cover the remaining undocumented items in other parts of the codebase.

docs: add module and function documentation

---

CHANGELOG.md
miden-crypto/benches/merkle.rs
miden-crypto/benches/smt-subtree.rs
miden-crypto/benches/smt-with-entries.rs
miden-crypto/benches/smt.rs
miden-crypto/src/hash/rescue/rpo/digest.rs
miden-crypto/src/hash/rescue/rpx/digest.rs
miden-crypto/src/main.rs
miden-crypto/src/merkle/mmr/partial.rs
miden-crypto/src/merkle/smt/full/concurrent/tests.rs
miden-crypto/src/merkle/sparse_path.rs

Closes #412 
I solved some `cargo +nightly clippy --workspace --all-targets --all-features` issues 
Fix 

fix: replace deprecated #[clap(...)] with #[command(...)] and #[arg(...)]

---

CHANGELOG.md
miden-crypto/src/merkle/index.rs
miden-crypto/src/merkle/mod.rs
miden-crypto/src/merkle/smt/full/error.rs
miden-crypto/src/merkle/smt/full/leaf.rs
miden-crypto/src/merkle/smt/full/mod.rs
miden-crypto/src/merkle/smt/full/proof.rs
miden-crypto/src/merkle/smt/mod.rs

docs: add module and function documentation-2

---

CHANGELOG.md
Cargo.lock
miden-crypto/Cargo.toml
miden-crypto/src/word.rs

First step towards closing https://github.com/0xMiden/miden-base/issues/1373

feat: add word! macro to miden-crypto

---

CHANGELOG.md
miden-crypto/src/merkle/smt/full/mod.rs
miden-crypto/src/merkle/smt/partial.rs

Closes #416 
Adds missing `PartialSmt` APIs

feat: add PartialSmt APIs

---

CHANGELOG.md
miden-crypto/src/main.rs
miden-crypto/src/merkle/error.rs
miden-crypto/src/merkle/smt/full/concurrent/mod.rs
miden-crypto/src/merkle/smt/full/concurrent/tests.rs
miden-crypto/src/merkle/smt/full/leaf.rs
miden-crypto/src/merkle/smt/full/mod.rs
miden-crypto/src/merkle/smt/full/tests.rs
miden-crypto/src/merkle/smt/mod.rs
miden-crypto/src/merkle/smt/partial.rs
miden-crypto/src/merkle/smt/simple/mod.rs
miden-crypto/src/merkle/smt/simple/tests.rs

Follow-up from https://github.com/0xMiden/crypto/pull/455

Errors instead of panics when inserting too many leaf entries

---

CHANGELOG.md
README.md
miden-crypto/src/merkle/mod.rs
miden-crypto/src/merkle/smt/full/mod.rs
miden-crypto/src/merkle/smt/full/proof.rs
miden-crypto/src/merkle/smt/mod.rs
miden-crypto/src/merkle/smt/partial.rs
miden-crypto/src/merkle/smt/simple/mod.rs
miden-crypto/src/merkle/smt/simple/proof.rs
miden-crypto/src/merkle/sparse_path.rs

Use SparseMerklePath in Smt proofs

---

CHANGELOG.md
README.md
miden-crypto/benches/README.md
miden-crypto/benches/hash.rs
miden-crypto/src/hash/blake/mod.rs
miden-crypto/src/hash/keccak/mod.rs
miden-crypto/src/hash/keccak/tests.rs
miden-crypto/src/hash/mod.rs

Add Keccak256

---

README.md

Update read-me file with ECDSA and ECDH

---

miden-crypto/benches/encryption.rs
miden-crypto/src/aead/aead_rpo/mod.rs
miden-crypto/src/aead/mod.rs
miden-crypto/src/aead/xchacha/mod.rs
miden-crypto/src/aead/xchacha/test.rs
miden-crypto/src/dsa/ecdsa_k256_keccak/mod.rs
miden-crypto/src/utils/mod.rs

Chore: restore Felt methods for XChaCha

---

miden-crypto/src/merkle/smt/full/mod.rs

Adds some visual docs to explain how the SMT is structured.

better doc comment
