0xMiden/crypto

- .github/pull_request_template.md
- .github/workflows/ci.yml
- CONTRIBUTING.md
- Cargo.toml
- crypto/src/hash/mod.rs
- crypto/src/lib.rs
Currently the API modules are hidden to the crate scope.
In order to avoid global permissive allows, they can initially be
exported, and tweaked to local scopes as they get implemented, finalized
and tested.
Related to #3 
This commit introduces a workspace structure with a `Cargo.toml`.
Currently we have a single member `crypto`, but these can be added
incrementally in the future.
This commit introduces a script that will enforce the following
constraints:
- Tests are successful
- Rustfmt is executed for every Rust source
- Clippy warnings are resolved
The same model of Miden VM is adopted here. However, `no-std` check
wasn't added because the library, as of the moment, doesn't implement
that.
closes #3 
The contributing guidelines are defiend as standard for Miden VM and it
is desirable …
> feat(ci): add script to ci

- Cargo.toml
- src/hash/blake/mod.rs
- src/hash/blake/tests.rs
- src/hash/mod.rs
> feat: add blake3 160, 192 & 256 bits

- Cargo.toml
- benches/hash.rs
- src/hash/blake/mod.rs
- src/hash/blake/tests.rs
- src/hash/mod.rs
- src/hash/rpo/digest.rs
- src/hash/rpo/mds_freq.rs
- src/hash/rpo/mod.rs
- src/hash/rpo/tests.rs
- src/lib.rs
- src/merkle/merkle_path_set.rs
- src/merkle/merkle_tree.rs
- src/merkle/mod.rs
This PR cleans up create interfaces in preparation for v0.1 release. Specifically:
* Better groups external interfaces and removes un-needed re-exports.
* Deletes inverse MDS matrix as we no longer needed for constraint evaluation.
* Renames `RpoDigest256` into just `RpoDigest`. If we need a digest with a different number of elements, we should be able to use the same approach as with `Blake3Digest`.
* Adds pass-through methods to all hasher implementations (e.g., `hash()`, `hash_elements()`). This is so that we don't have to drag `Hasher` and `ElementHasher` traits around everywhere. If there is a better way to do this, I'm happy to change this.
* Adds missing constants and a couple of trait implementations which would be useful for external consumption.
> Clean up crate interfaces in preparation for v0.1 release

- src/hash/blake/mod.rs
- First convert all `Felts` to their canonical form and write into preallocated buffer, in little-endian byte order
- Finally hash all input bytes by calling BLAKE3 hasher **only once**
---
At commit 9782992662c1c01e89d0c55de220a1235877abdc ( before )
At commit aa4e31369017c6093b171f4302c6908751b43575 ( after )
> Optimize BLAKE3 Sequential Hashing

- src/hash/blake/mod.rs
This PR came about as a result of the discrepancy noticed in https://github.com/0xPolygonMiden/crypto/pull/26#issuecomment-1344540033. The surprising result is that changing from an iterator to a for loop led to over 4x improvement in sequential hashing of elements using BLAKE3. So, the new performance on my machine looks like 1.7us for hashing 100 elements (vs. 7us previously).
This performance is still lower than what I would have expected (i.g., I would have thought it would be around 1.2us) - but at least there might be a reasonable explanation for this now.
Separately, I noticed that there might be a small optimization opportunity in Winterfell. Specifically, in the [as_int()](https://github.com/novifinancial/winterfell/blob/main/math/src/field/f64/mod.rs#L229) we know that the value …
> Improve BLAKE3 sequential hashing performance

- Cargo.toml
- benches/smt.rs
- src/lib.rs
- src/merkle/merkle_tree.rs
- src/merkle/mod.rs
- src/merkle/simple_smt/mod.rs
- src/merkle/simple_smt/tests.rs
This commit moves the previous implementation of `SparseMerkleTree` from
miden-core to this crate.
It also include a couple of new tests, a bench suite, and a couple of
minor fixes. The original API was preserved to maintain compatibility
with `AdviceTape`.
closes #21
> feat: add simple sparse merkle tree

- src/merkle/merkle_path_set.rs
- src/merkle/merkle_tree.rs
- src/merkle/simple_smt/mod.rs
Tiny PR to add `PartialEq` and `Eq` derives to Merkle tree structs.
> Implement PartialEq and Eq traits on Merkle structs

- src/lib.rs
This PR addresses #39. It reexports `PublicCoin` and `PublicCoinError` from winterfell.
> Reexport publiccoin & publiccoinerror from winterfell

- src/hash/rpo/mod.rs
- src/hash/rpo/tests.rs
This PR addresses #35. It introduces a new method `merge_in_domain` as mentioned by @bobbinth [here](https://github.com/0xPolygonMiden/crypto/issues/35#issuecomment-1380989610) when impl Rpo256.
> Domain separator during merge

- src/hash/rpo/tests.rs
This PR address @bobbinth's comment [here](https://github.com/0xPolygonMiden/crypto/pull/40#discussion_r1084780789).
> refactor merge in domain tests

- src/hash/rpo/mod.rs
- src/hash/rpo/tests.rs
> fix: sponge pad panics on input

- src/merkle/merkle_tree.rs
- src/merkle/mod.rs
- src/merkle/path.rs
- src/merkle/path_set.rs
- src/merkle/simple_smt/mod.rs
- src/merkle/simple_smt/tests.rs
A Merkle path is a vector of nodes, regardless of the Merkle tree implementation.
This commit introduces an encapsulation for such vector, also to provide functionality that is common between different algorithms such as opening verification.
related issue: #36
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> feat: add merkle path wrapper

- README.md
- src/lib.rs
- src/merkle/index.rs
- src/merkle/merkle_tree.rs
- src/merkle/mod.rs
- src/merkle/path.rs
- src/merkle/path_set.rs
- src/merkle/simple_smt/mod.rs
- src/merkle/simple_smt/tests.rs
This commit introduces a wrapper structure to encapsulate the merkle tree traversal.
related issue: #36
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> feat: add merkle node index

- src/merkle/index.rs
While working on https://github.com/0xPolygonMiden/crypto/pull/67 I looked into using `NodeIndex`, however this structure uses level form, whereas the MMR uses postorder form, so it couldn't be used.
This just adds a bit of documentation for that detail, hopefully making that easier for the next person to spot.
> docs: mention tree form order of NodeIndex docs

- src/merkle/mmr/accumulator.rs
- src/merkle/mmr/bit.rs
- src/merkle/mmr/full.rs
- src/merkle/mmr/mod.rs
- src/merkle/mmr/proof.rs
- src/merkle/mmr/tests.rs
- src/merkle/mod.rs
- src/merkle/simple_smt/tests.rs
This is a all in-memory fully materialized MMR implementation.
The most frequent operation on the tree is appending a new element, so this implementation "optimizes" for that and just appends the new elements to the end of a vector. This means the vector represents a forest (multiple trees), all in a postorder sequential representation. The parent nodes are computed eagerly whenever pairs become available.
> feat: merkle mountain range

- benches/smt.rs
- src/hash/rpo/digest.rs
- src/merkle/empty_roots.rs
- src/merkle/mod.rs
- src/merkle/simple_smt/mod.rs
- src/merkle/simple_smt/tests.rs
Prior to this commit, there was an internal procedure with the merkle trees to compute empty sub-tree for arbitrary depths.
However, this isn't ideal as this code can be reused in any merkle implementation that uses RPO as backend.
This commit introduces a structure that will generate these empty subtrees values.
> feat: refactor simple smt to use empty subtree constants

- src/merkle/store.rs
Instead of returning the root directly, now a query is performed to check the storage contains the root.
> bugfix: check if the requested root is in the storage

- src/merkle/mod.rs
- src/merkle/store/mod.rs
- src/merkle/store/tests.rs
The store builds the path from root to leaf, this updates the code to return a path from leaf to root, as it is done by the other structures.
> bugfix: reverse merkle path to match other structures

- src/bit.rs
- src/merkle/mod.rs
- src/merkle/path_set.rs
- src/merkle/store.rs
- src/merkle/store/mod.rs
- src/merkle/store/tests.rs
Prior to this commit, the MerkleStore panicked under certain bounds. It will prevent such panics by using checked operations.
ilog2, for instance, will panic when the operand is zero. However, there is a documentation rule enforcing the merkle tree to be size at least 2. If this rule is checked, then the panic is impossible.
> fix: merkle store panics on bounds

- benches/store.rs
It seems that https://github.com/0xPolygonMiden/crypto/pull/99 and https://github.com/0xPolygonMiden/crypto/pull/97 were merged at the same time, the first had a breaking API change, this fixes makes the benchmark code introduced by the later compatible with the new API.
> Fix benchmark code

- src/merkle/index.rs
- src/merkle/path_set.rs
- src/merkle/store/mod.rs
- src/merkle/store/tests.rs
This PR fixes a couple of issues with `MerklePathSet`. Specifically:
- The depth in `MerklePathSet` is now treated the same way is in other Merkle structures (previously was off by 1).
- Reduction of `MerklePathSet` to a set of paths now takes into account all indexes contained in the `MerklePathSet`.
- Also fixed a couple of typos and simplified path key computations.
> Fix MerklePathSet issues

- src/merkle/store/mod.rs
- src/merkle/store/tests.rs
The path returned by `EmptySubtreeRoots` starts at the root, and goes to the leaf. The MerkleStore constructor assumed the other direction, so the parent/child hashes were reversed.
This fixes the bug and adds a test.
> bugfix: fix internal nodes of for empty leafs of a SMT

- README.md
- benches/store.rs
- src/merkle/simple_smt/mod.rs
- src/merkle/store/mod.rs
- src/merkle/store/tests.rs
Prior to this commit, MerkleStore allowed the creation of Sparse Merkle tree only with the maximum depth of 63. However, this doesn't fit the Tiered Sparse Merkle tree requirements, as it will contain trees of depth 16.
This commit adds the `depth` argument to the MerkleStore methods that will create Sparse Merkle trees.
> feat: Add `depth` as store SMT argument

- src/merkle/simple_smt/mod.rs
- src/merkle/store/mod.rs
This is just a small simplification to the codebase. ATM the Store is not useful for much, and adds an extra layer of indirection that seems unnecessary for the time being.
We can add this later on if necessary (or not merge this, it is just a suggestion and it was a quick one to make)
edit: the original title was super confusing, I didn't mean the structure named `MerkleStore`, I meant the struct `Store` inside the `merkle::siple_smt` module. Sorry for any confusion, I have renamed the PR.
> Remove SimpleSmt store

- src/merkle/mmr/full.rs
- src/merkle/mmr/tests.rs
- src/merkle/store/mod.rs
This adds support to importing the nodes of an MMR to the MerkleStore. The goal is to make testing of the Masm implementation easier to test (and this may be useful to initialize the store for the VM too).
review/merge after #117 
> feat: add support for MMR to the MerkleStore

- src/merkle/simple_smt/mod.rs
- src/merkle/simple_smt/tests.rs
- src/merkle/store/mod.rs
This adds the parent node iterator, and no longer exposes the internal of the struct (as discussed on https://github.com/0xPolygonMiden/crypto/pull/116#discussion_r1153918263)
review/merge after: https://github.com/0xPolygonMiden/crypto/pull/117
> feat: add parent node iterator for SimpleSMT

- src/merkle/store/mod.rs
- src/merkle/store/tests.rs
This commit introduces `get_leaf_depth`, a tiered SMT helpers that will retrieve the depth of a leaf for a given root, capped by `64`.
closes #119
> feat: add `MerkleStore::get_leaf_depth`

- benches/README.md
- src/hash/blake/mod.rs
- src/hash/blake/tests.rs
This PR switches from vector to array buffer when hashing elements using `BLAKE3` hash function. On my machine (Apple M1 Pro), this change results in about 7.5% improvement for the sequential hashing benchmark.
> BLAKE3 hash_elements() optimization

- src/merkle/mod.rs
This PR exports `MmrProof` such that is is part of the public interface of the `crypto` crate.
> re-export mmr proof

- src/merkle/store/mod.rs
Consider the case of a MMR with one entry and a new entry is being added. Both of these values are quite unique, they are at the same time the root and only leaf of their corresponding tree. Currently this representation is not supported by the [MerkleStore], so this data is not in it, but once the two values are merged, they both become leaves of a new tree under the new parent.
The existing validation didn't permit that promotion from happening, which meant a [Mmr] couldn't be implemented with the method `merge_roots`.
This lifts the validation, and changes the method to clarify that not only `root` are being merged, by arbitrary nodes of a tree (leafs, internal, or roots), with arbitrary mixing of each.
- …
> feat: allow merging of leaves

- benches/store.rs
- src/merkle/merkle_tree.rs
- src/merkle/path.rs
- src/merkle/store/mod.rs
- src/merkle/store/tests.rs
fixes #136   
implemented the extend trait for the merkle store, consume an iterator over inner nodes. this can be used to add existing structures into the store.
> store: support adding existing structures

- src/merkle/store/mod.rs
This PR introduces the `.inner_nodes()` method on `MerkleStore` which allows one merkle store to be extended by the contents of the other like so:
```rust
merkle_store.extend(other_merkle_store.inner_nodes());
```
closes: #142 
> feat: add .inner_nodes() to [MerkleStore]

- benches/smt.rs
- benches/store.rs
- src/merkle/empty_roots.rs
- src/merkle/mod.rs
- src/merkle/simple_smt/mod.rs
- src/merkle/simple_smt/tests.rs
- src/merkle/store/tests.rs
This PR addresses #143 and #144 and cleans up `SimpleSmt` struct as follows:
- Updates and normalizes method comments.
- Changes `with_leaves()` constructor to take `depth` as a parameter. This makes working with `SimpleSmt` easier.
- Returns an error if `with_leaves()` constructor with invoked with entries containing duplicate keys.
- Consolidates `update_leaf()` and `insert_leaf()` into a single method since both of these basically did the same thing.
- Removes `leaves_count()` method as number of leaves in a `SimpleSmt` is equal to $2^{depth}$, and tracking non-empty leaf count is not trivial.
- Adds `get_leaf()` method.
- Cleans up tests and removes proptests which didn't seem to be doing much.
> SimpleSmt updates

- src/merkle/merkle_tree.rs
- src/merkle/simple_smt/mod.rs
- src/merkle/store/mod.rs
- src/merkle/store/tests.rs
This PR adds `MerkleStore::subset()` method to address #141. It also adds `leaves()` method to `MerkleTree` and `SimpleSmt`. The latter one addresses #150.
> MerkleStore subset and more

- src/hash/rpo/digest.rs
- src/merkle/index.rs
- src/merkle/mod.rs
- src/merkle/path_set.rs
- src/merkle/simple_smt/mod.rs
- src/merkle/tiered_smt/mod.rs
- src/merkle/tiered_smt/tests.rs
This PR implements basic Tiered SMT in Rust. This implementation lives fully in memory.
The basic implementation covers pretty much everything except for the following:
- Deletions are not yet supported.
- Iteration over inner nodes is not yet supported.
- Bottom tier node hash computation does not use `merge_in_domain()`.
> Basic Tiered MST

- src/merkle/index.rs
- src/merkle/store/mod.rs
- src/merkle/tiered_smt/mod.rs
- src/merkle/tiered_smt/tests.rs
This PR implements iterators over the contents of `TieredSmt` introduced in #152.
This should also address #135 as we'd be able to instantiate or extend `MerkleStore` from a `TieredSmt`.
> Tiered SMT iterators

- CHANGELOG.md
- Cargo.toml
- benches/smt.rs
- benches/store.rs
- src/hash/rpo/digest.rs
- src/merkle/empty_roots.rs
- src/merkle/index.rs
- src/merkle/merkle_tree.rs
- src/merkle/mmr/accumulator.rs
- src/merkle/mmr/mod.rs
- src/merkle/mod.rs
- src/merkle/path_set.rs
- src/merkle/simple_smt/mod.rs
- src/merkle/simple_smt/tests.rs
- src/merkle/store/mod.rs
- src/merkle/store/tests.rs
- src/merkle/tiered_smt/mod.rs
- src/merkle/tiered_smt/tests.rs
This PR tracks progress for v0.5 release. The aim of this release is primarily to wrap up implementations various Merkle structures.
As a part of this release we should close the following issues (one way or the other):
One question is what are we looking for in the Rust implementation of the tiered SMT. In my mind, we'd use it for account storage and vaults and so the requirements should be driven by the needs of the account object.
There are two other use cases for a tiered SMT: (1) account database, and (2) nullifier database. Both of these will probably require different implementations as they are going to be too large for pure in-memory implementation. So, we'll do them in future releases.
Current implementation of the MMR is good enough for the needs of the chain database, but for …
> Tracking PR for v0.5 release

- benches/store.rs
- src/hash/rpo/tests.rs
- src/merkle/merkle_tree.rs
- src/merkle/mmr/accumulator.rs
- src/merkle/mmr/full.rs
- src/merkle/mmr/tests.rs
- src/merkle/mod.rs
- src/merkle/node.rs
- src/merkle/path.rs
- src/merkle/path_set.rs
- src/merkle/simple_smt/mod.rs
- src/merkle/simple_smt/tests.rs
- src/merkle/store/mod.rs
- src/merkle/store/tests.rs
- src/merkle/tiered_smt/mod.rs
- src/merkle/tiered_smt/tests.rs
Addressing #131. Replaces `Word` in the structures in the crypto crate to `RpoDigest` to avoid unnecessary conversions and to maintain consistency.
> refactor: refactor crypto APIs to use RpoDigest instead of Word

- src/merkle/mod.rs
- src/merkle/partial_mt/mod.rs
- src/merkle/partial_mt/tests.rs
- src/merkle/store/mod.rs
- src/utils.rs
Implementation of basic functionality for Partial Merkle tree similar to Sparse Merkle tree.
(De)serialization of this structure will be implemented in future PR.
> Partial Merkle tree implementation

- src/merkle/store/mod.rs
- src/utils/diff.rs
- src/utils/kv_map.rs
- src/utils/mod.rs
This PR introduces functionality:
- `DiffT` trait that specifies the interface for computing the diff between two objects.
- `ApplyDiffT` trait that specifies the interface for applying a diff to a target object.
- Implementation of `DiffT` and `ApplyDiffT` on `MerkleStore` and `KvMap` (trait).
- Introduction of `KvMapDiff` that represents the diff between `KvMap` and by association `MerkleStore`.
- Introduction of `remove(..)` for `KvMap`.
> feat: introduce `Diff` traits and objects

- src/merkle/delta.rs
- src/merkle/mod.rs
- src/merkle/simple_smt/mod.rs
- src/merkle/store/mod.rs
- src/merkle/store/tests.rs
- src/utils/diff.rs
- src/utils/kv_map.rs
This PR introduces the following changes:
- `TryApplyDiff` trait which is provides an interface for applying a diff which is fallible. 
- Implements `TryApplyDiff` trait for `SimpleSmt`.
- Introduces `MerkleStoreDelta` and `MerkleDelta` objects which are responsible for holding `MerkleStore` and generic merkle tree detlas respectively.
- Introduces `merkle_tree_delta(..)` method on `MerkleStore` to extract `MerkleDelta`.
- Modifies `RecordingMap` finalizer to return the underlying data that contains the current state of the map as well as the proof.
> Introduce TryApplyDiff and refactor RecordingMap finalizer

- src/merkle/partial_mt/mod.rs
- src/merkle/tiered_smt/mod.rs
- src/merkle/tiered_smt/nodes.rs
- src/merkle/tiered_smt/tests.rs
- src/merkle/tiered_smt/values.rs
This PR implements clearing of values in TSMT which happens when `EMPTY_VALUE` is inserted at a given key. To achieve this, I refactored the TSMT to consist of 2 components: `ValueStore` and `NodeStore`. `ValueStore` in particular provided a good abstraction for looking up key-value pairs using `range()` method of `BTreeMap`.
Introducing `NodeStore` was not technically required, but I think the overall construction is now cleaner, and in the future, we could make `TieredSmt` more flexible by specifying `ValueStore` and `NodeStore` via generic parameters (e.g., `ValueStore` could have a database-backed implementation in the future).
It also simplifies leaf hashing according to the methodology described in #159.
> Implement value clearing in TSMT

- Cargo.toml
- src/hash/blake/mod.rs
- src/hash/rpo/digest.rs
- src/merkle/delta.rs
- src/merkle/index.rs
- src/merkle/merkle_tree.rs
- src/merkle/mmr/accumulator.rs
- src/merkle/mmr/full.rs
- src/merkle/mmr/proof.rs
- src/merkle/node.rs
- src/merkle/partial_mt/mod.rs
- src/merkle/path.rs
- src/merkle/simple_smt/mod.rs
- src/merkle/store/mod.rs
- src/merkle/tiered_smt/mod.rs
- src/merkle/tiered_smt/nodes.rs
- src/merkle/tiered_smt/values.rs
- src/utils/mod.rs
Adds conditional support to serde. This can be used to serialize the data as JSON to encode the mock chain data.
This depends on https://github.com/facebook/winterfell/pull/209
> feature: add conditional support for serde

- src/hash/blake/mod.rs
Required to use `Blake3Digest` as keys in a map. (For https://github.com/0xPolygonMiden/miden-vm/issues/990)
> feat: derive ord and partialord for blake3digest

- Cargo.toml
- src/hash/rpo/digest.rs
- src/main.rs
- src/merkle/tiered_smt/mod.rs
This PR performs a benchmark of the Tiered Sparse Merkle Tree. Construction, Insertion and Proof generation were tested. Tree with 1K and 1M entries was tested. Each test was running 5 times. 
Results: 
|   | Entries number                  |        |
| - | ------------------------------- | ------ |
|   | 1K                              | 1M     |
| # | Construction (seconds)          |        | 
| 1 | 0.120                           | 211.78 | 
| 2 | 0.122                           | 217.05 | 
| 3 | 0.121                           | 214.63 | 
| 4 | 0.122                           | 214.99 | 
| 5 | 0.122                           | 211.02 | 
| # | Insertion (microseconds)        |        | 
| 1 | 100                             | 205    |  
| 2 | 100                             | 213    | …
> Benchmark of the Tiered SMT

- CHANGELOG.md
- src/merkle/path.rs
- src/merkle/store/mod.rs
- src/merkle/store/tests.rs
- src/merkle/tiered_smt/mod.rs
This PR adds a couple of leaf traversal methods to `MerkleStore` needed to support deletion functionality in MASM implementation of TSMT.
Specifically, the following methods were added:
- ~`get_leaf_path` - which returns a path to the first leaf or an empty node for the specified index.~
- `find_lone_leaf` - which can be used to determine if a given subtree contains just a single leaf node.
~Also, as a part of this PR `get_leaf_depth` was refactored and renamed into `find_first_leaf` to align better with the needs of the advice injectors which currently use this method.~
> Add more leaf traversal methods for `MerkleStore`

- src/hash/rpo/mds_freq.rs
- src/hash/rpo/tests.rs
- src/lib.rs
- src/merkle/delta.rs
- src/merkle/empty_roots.rs
- src/merkle/mod.rs
- src/merkle/partial_mt/mod.rs
- src/merkle/simple_smt/mod.rs
- src/merkle/simple_smt/tests.rs
- src/merkle/store/mod.rs
- src/merkle/store/tests.rs
- src/merkle/tiered_smt/mod.rs
- src/merkle/tiered_smt/tests.rs
This PR adds a new `EMPTY_WORD` constant replacing with it all usages of `[ZERO; 4]`, `[ZERO, ZERO, ZERO, ZERO]` and `[ZERO; WORD_SIZE]`, along with replacing `Felt::ZERO` and `Felt::new(0)` with `ZERO`, `Felt::ONE` and `Felt::new(1)` with ONE.
> Create empty word constant

- Cargo.toml
- README.md
This PR prepares `miden-crypto` crate for v0.7 release. Specifically:
- I added a section about signature schemes to the main readme.
- I bumped up dependency versions and min Rust version (to 1.73).
> v0.7 release prep

- CHANGELOG.md
- src/merkle/merkle_tree.rs
- src/merkle/mmr/delta.rs
- src/merkle/mmr/error.rs
- src/merkle/mmr/full.rs
- src/merkle/mmr/inorder.rs
- src/merkle/mmr/mod.rs
- src/merkle/mmr/partial.rs
- src/merkle/mmr/peaks.rs
- src/merkle/mmr/proof.rs
- src/merkle/mmr/tests.rs
- src/merkle/mod.rs
- src/merkle/path.rs
Note: I'm adding a few more test, a preliminary review can be useful but I will push some additional code today.
This differs significantly to the #86 . That PR implemented a data structure that could track a single element, i.e. a single authentication path from a Mmr. This implements a structure that can track an arbitrary number of elements (from just the peaks/0 leaves, up to every leaf in the Mmr).
- The first iteration was based on `Vec<MerklePath>`. Each element in the vector was one authentication path to be updated in isolation. Issues:
- Being a vector of vectors, to figure out the peaks of the `PartialMmr` one would need to iterate over all the `MerklePath`s
- Updates would potentially result into dozens of allocations (the higher end for this structure is in the low thousands, …
> mmr: added partial mmr

- src/merkle/mmr/full.rs
- src/merkle/mmr/tests.rs
Adds support for getting the opening to a different Mmr version.
This is required by the state sync endpoint, since it doesn't always send the opening w.r.t. the latest Mmr.
> mmr: support proofs with older forest versions

- src/merkle/mmr/peaks.rs
Allows one to consume the object and get a hand of the peaks vector.
> mmr: add into_parts for the peaks

- src/dsa/rpo_falcon512/keys.rs
- src/dsa/rpo_falcon512/signature.rs
Was reading code and saw this TODO to memoize, assumed this would be what was intended.
There was a similar one for the `KeyPair` public key commitment, but I didn't include with these as it would remove the `Copy` derivation, and I wanted these changes to be less opinionated.
> feat: memoize Signature polynomial decoding

- src/merkle/index.rs
- src/merkle/simple_smt/mod.rs
- src/merkle/simple_smt/tests.rs
`update_leaf` was modifying the structure before validating the index, this allowed for invalid values to be insert in it.
> simplesmt: bugfix, index must be validated before modifying the tree

- src/merkle/simple_smt/mod.rs
- src/merkle/simple_smt/tests.rs
Introduces `SimpleSmt::with_contiguous_leaves()` which is useful to build a `SimpleSmt` from complex iterator expressions, and where we want to pack all the leaves from index 0 and on.
For example, this is now possible (a pattern needed in `miden-node` to build the created notes tree):
```rust
// simplified
SimpleSmt::with_contiguous_leaves(
DEPTH,
note_envelopes
.flat_map(|note| [note.note_hash(), note.metadata()])
.collect::<Vec<_>>(),
)
.unwrap();
```
> Introduce `SimpleSmt::with_contiguous_leaves()`

- src/merkle/simple_smt/mod.rs
- src/merkle/simple_smt/tests.rs
> simplesmt: simplify duplicate check

- src/merkle/error.rs
- src/merkle/partial_mt/mod.rs
- src/merkle/simple_smt/mod.rs
The `ExactSizeIterator` constraint forces the caller to instantiate iterators into, say, a `Vec`, which leads to useless memory allocations. The signature of the function is now cleaner as well.
The one downside of this approach is that in the unlikely case that the collection indeed has more than 2^63 elements, then we will do a lot of processing before figuring that out. However, this will almost never happen, and we should optimize for the case where the iterator doesn't have too many elements.
> Remove `ExactSizeIterator` constraint from `SimpleSmt::with_leaves()`

- src/merkle/error.rs
- src/merkle/simple_smt/mod.rs
- src/merkle/simple_smt/tests.rs
Closes #220 
Note that `set_subtree()` returns `Result<(), MerkleError>` [instead of](https://github.com/0xPolygonMiden/crypto/issues/220#issuecomment-1823911017) `Result<Word, MerkleError>`, because I didn't know which value to return. The hash of the internal node where the subtree root was inserted? Is this relevant information?
I would also suggest we change the interface to
```rust
pub fn set_subtree(&mut self, index: NodeIndex, subtree: SimpleSmt) -> Result<(), MerkleError>
```
This would result in caller code that's easier to read (since the depth of the insertion is determined at the call site). I believe callers should always know the depth at which they want to insert, such as in `miden-node` where we want to insert a subtree of depth 13 at depth 8.
> Implement `SimpleSmt::set_subtree`

- CHANGELOG.md
- README.md
- src/rand/mod.rs
- src/rand/rpo.rs
This moves the `RpoRandomCoin` to the `crypto` crate and defines a trait for generating random `Felt` and `Word` on it.
> Move RpoRandomCoin to crate

- CHANGELOG.md
- src/merkle/mmr/inorder.rs
- src/merkle/mmr/mod.rs
- src/merkle/mmr/partial.rs
- src/merkle/mmr/peaks.rs
- src/merkle/path.rs
This PR implements `inner_node()` iterator for `PartialMmr` so that we can insert authentication paths from `PartialMmr` into a `MerkleStore`.
> Implement `inner_nodes()` iterator for `PartialMmr`

- src/merkle/mmr/inorder.rs
- src/merkle/mmr/partial.rs
This PR fixes a bug in `PartialMmr::apply_delta()` and adds tests to test this functionality more thoroughly. The bug was that authentication paths located in the left subtrees would not be extended when the trees would be mreged.
In addition to the above, this PR introduces a couple of small changes:
- `PartialMmr::apply_delta()` now returns a vector of nodes added to the Partial MMR's authentication node set as the result of the update.
- `PartialMmr::nodes()` method was added to return an iterator over all authentication nodes of the partial MMR.
> Improvements to `PartialMmr::apply_delta()`

- src/hash/rescue/arch/mod.rs
- src/hash/rescue/arch/x86_64_avx2.rs
- src/hash/rescue/mod.rs
- src/hash/rescue/rpo/mod.rs
- src/hash/rescue/rpx/mod.rs
It improves performance of the RPO hash function by leveraging AVX2 instructions on compatible x86_64 hardware (code based on plonky2: https://github.com/0xPolygonZero/plonky2/blob/main/plonky2/src/hash/arch/x86_64/poseidon_goldilocks_avx2_bmi2.rs). On AWS' Zen4 instance (c7a), I'm measuring 40% improvement against the baseline commit c86bdc6.
To leverage AVX2 implementation, code needs to be compiled with `RUSTFLAGS="-C target-feature=+avx2"`. Despite availability of AVX512 with larger register sizes, I wasn't able to leverage it for any additional speedups.
Below `RUSTFLAGS="-C target-feature=+avx2" cargo bench` improvement against the baseline `cargo bench`.
> feat: implement RPO hash using AVX2 instructions

- Cargo.toml
- README.md
- build.rs
- src/hash/rescue/arch/mod.rs
This PR removes a dedicated `sve` feature because we can enable it via `target_feature` flag instead.
> refactor: remove sve feature flag

- CONTRIBUTING.md
- src/merkle/mmr/full.rs
- src/merkle/store/tests.rs
tests: fix typos
full.rs: fix typo
CONTRIBUTING: fix typo
> Fix: typos

- src/hash/rescue/rpo/mod.rs
- src/hash/rescue/rpx/mod.rs
Addresses #203 
I have kept the old padding rule when hashing bytes so as to avoid the security degradation. On the other hand, there is also a case for uniformity so maybe we should also change it to the new padding rule.
> New padding rule for RPX

- src/dsa/rpo_falcon512/signature.rs
The deserialization of signatures was not working properly due to slicing the byte array twice. This PR fixes the issue and adds a test for round-trip serialization.
Fixes https://github.com/0xPolygonMiden/crypto/issues/265
> fix(dsa): fix deserialization logic

- src/hash/rescue/rpx/mod.rs
The intention with the RPX new padding rule was to always pad the bytes with 10*0 but for some reason this wasn't included in the original PR. This one fixes that.
> Pad bytes with 10*0

- src/merkle/smt/full/mod.rs
- src/merkle/smt/full/tests.rs
> Add missing methods to `Smt`

- src/merkle/smt/full/mod.rs
- src/merkle/smt/full/tests.rs
- src/merkle/smt/mod.rs
- src/merkle/smt/simple/mod.rs
Closes: #246
Fixes the test breaking in https://github.com/0xPolygonMiden/miden-base/pull/449
> `Smt`: remove inner nodes when removing value

- src/merkle/mod.rs
- src/merkle/smt/mod.rs
Re-exports 2 types that were introduced in #270, and forgotten to be re-exported
> Re-export `SmtProof` and `SmtProofError`

- src/hash/rescue/rpo/mod.rs
- src/hash/rescue/rpo/tests.rs
- src/hash/rescue/rpx/mod.rs
The 2021 prelude includes TryFrom and TryInto [1]. And recently the nigtlhy channel started linting for this duplicated imports and emitting warnings. This removes the redundant imports.
1: https://doc.rust-lang.org/core/prelude/rust_2021/index.html
---
Here is an example warning:
```
warning: the item `TryInto` is imported redundantly
--> src/hash/rescue/rpo/mod.rs:7:12
|
7   | use core::{convert::TryInto, ops::Range};
|            ^^^^^^^^^^^^^^^^
|
::: /Users/hack/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/prelude/mod.rs:129:13
|
129 |     pub use core::prelude::rust_2021::*;
|             ------------------------ the item `TryInto` is already defined here
```
- Commit …
> clippy: fix TryFrom/TryInto warnings

- src/utils/mod.rs
This has to be merged after facebook/winterfell#263.
With the changes in that PR we unintentionally removed the `vec` and `format` macros from the `miden-crypto` public API.
> fix: re-add unintentionally removed re-exported liballoc macros

- CHANGELOG.md
- Cargo.lock
- src/rand/mod.rs
- src/rand/rpo.rs
This PR adds `RngCore` as a supertrait for `FeltRng`. This provides an easy way to fill a slice with random bytes for anything that implements `FeltRng`.
> Add `RngCore` supertrait for `FeltRng`

- src/merkle/smt/simple/mod.rs
Implemented leaf count to `SimpleSmt`. It's needed for serialization of the notes tree.
I've recreated branch and PR due to difficulties rebasing those branch on main.
Old PR: https://github.com/0xPolygonMiden/crypto/pull/301
> Added leaf count to `SimpleSmt`

- CHANGELOG.md
- src/merkle/smt/simple/mod.rs
- src/merkle/smt/simple/tests.rs
I realized the Simple SMT does not remove empty values from its `leaves` vector upon insert. This would have led to an incorrect leaf count after an `EMPTY_VALUE` is inserted into the tree. This PR fixes this.
Also, I renamed `leaf_count()` to `num_leaves()` as it is more consistent with our naming methodology and added a simple test to ensure that leaf count behaves as expected.
> Decrement leaf count in simple SMT when inserting empty value

- src/dsa/rpo_falcon512/keys/mod.rs
- src/dsa/rpo_falcon512/keys/secret_key.rs
- src/dsa/rpo_falcon512/math/mod.rs
This addresses the raised in https://github.com/0xPolygonMiden/miden-base/issues/616
The problem was due to the order of the secret key basis. 
> Fix Falcon bug

- src/hash/rescue/rpo/digest.rs
- src/hash/rescue/rpx/digest.rs
- src/merkle/smt/full/tests.rs
While writing the issues for the proposed trait implementations I noticed some missing conversions. This adds a bunch.
Note: This is a backwards incompatible change, because now there are multiple conversions for arrays. However, I think the new code is actually shorter and easier to use.
> Rpo256: Add RpoDigest conversions

- src/utils/mod.rs
The utility `hex_to_bytes` is also used to decode [the `init_seed`](https://github.com/0xPolygonMiden/miden-node/blob/c4747bb81a8f6037dd634c165958b67ecab9564e/bin/node/src/commands/genesis/mod.rs#L123-L124) in the client. The current error message is confusing when the length of the `init_seed` is incorrect.
> hex: `hex_to_bytes` can be used for data besides RpoDigests

- CHANGELOG.md
- src/merkle/mmr/full.rs
- src/merkle/mmr/partial.rs
- src/merkle/mmr/tests.rs
This PR renames `Mmr::open()` into `Mmr::open_at()` and `Mmr::peaks()` into `Mmr::peaks_at()` and also introduces `Mmr::open()` and `Mmr::peaks()` which rely on `Mmr::open_at()` and `Mmr::peaks()` respectively.
This makes the API a bit more ergonomic when we are working with the latest state of the MMR. For example, things like `mmr.open(leaf_pos, mmr.forest()` become just `mmr.open(leaf_pos)`.
As an aside, `open()` method is a bit inconsistent as it doesn't actually return the leaf at the specified position. To improve it further, we'd need to either modify the `MmrProof` to include the leaf, or return `(MmrProof, RpoDigest)` from `open()`. But I left it for future PRs.
> Minor improvements to the MMR API

- CHANGELOG.md
- src/main.rs
- src/merkle/empty_roots.rs
- src/merkle/mod.rs
- src/merkle/smt/full/leaf.rs
- src/merkle/smt/full/mod.rs
- src/merkle/smt/full/tests.rs
- src/merkle/smt/mod.rs
- src/merkle/smt/simple/mod.rs
This PR is first set for validating modifications to Merkle tree structures before committing the mutations (#222). With this, a key-value insertion with a known expected root can be safely performed without cloning the tree first. Once this is generalized to multiple insertions, tree clones like like https://github.com/0xPolygonMiden/miden-node/blob/72e7a5374fbe78dfe30d6cbbd4b78fff56730171/crates/store/src/state.rs#L235-L245 can be eliminated in an immediate step towards 0xPolygonMiden/miden-node#149. Going forward I will likely generalize this further to a transactional commit/rollback model.
- Relevant issues are linked in the PR …
> towards #222: implement transactional Smt insertion

- CHANGELOG.md
- src/merkle/mmr/inorder.rs
- src/merkle/mmr/partial.rs
This PR adds de-serialization for `PartialMmr` and `InOrderIndex`, with the corresponding tests.
This feature is needed for https://github.com/0xPolygonMiden/miden-base/issues/860 .
> feat: add de/serialization to `InOrderIndex` and `PartialMmr`

- CHANGELOG.md
- src/hash/rescue/rpo/digest.rs
- src/hash/rescue/rpx/digest.rs
Adds a `get_size_hint` implementation for `RpoDigest` and `RpxDigest`. This is required to nicely implement `get_size_hint` for custom types in miden-base, see also: https://github.com/0xPolygonMiden/miden-base/pull/895.
The added tests currently fail, but once https://github.com/facebook/winterfell/pull/332 is merged, they no longer will.
> feat: Add size hint for digests

- Cargo.lock
- src/merkle/smt/full/mod.rs
Implement `get_size_hint` for `Smt`.
Needed for https://github.com/0xPolygonMiden/miden-base/pull/895.
Non-breaking change targetted at `main` so it can be released in a patch release.
> Implement `get_size_hint` for `Smt`

- CHANGELOG.md
- src/merkle/mmr/error.rs
- src/merkle/mmr/peaks.rs
- src/merkle/mmr/tests.rs
- src/merkle/path.rs
- src/merkle/store/tests.rs
This small PR handles the panic case during the verification of the Merkle proof. 
Instead of a boolean value now the `verify()` procedures return the `Result<>` value, returning an error in case if provided MMR peak is out of bounds or the verification failed. 
Closes: #332
> Return error instead of panic during MMR verification

- CHANGELOG.md
- src/merkle/smt/full/mod.rs
- src/merkle/smt/full/tests.rs
- src/merkle/smt/mod.rs
- src/merkle/smt/simple/mod.rs
- src/merkle/smt/simple/tests.rs
This tiny PR implements the `is_empty()` function for the `SimpleSmt` and `Smt` structures. 
It also provides a new `EMPTY_ROOT` constant to the `SparseMerkleTree` trait, which equals to the root of empty tree with specified depth.
> Add `Smt::is_empty`

- CHANGELOG.md
- src/rand/rpo.rs
Fixes a bug where we used the element containing the all zero prefix to sample query indices. The previous implementation always sampled index 0.
> Skip using the field element containing the proof-of-work

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/hash/rescue/rpo/digest.rs
- src/hash/rescue/rpx/digest.rs
- src/merkle/error.rs
- src/merkle/index.rs
- src/merkle/mmr/error.rs
- src/merkle/mmr/full.rs
- src/merkle/mmr/partial.rs
- src/merkle/mmr/peaks.rs
- src/merkle/partial_mt/mod.rs
- src/merkle/path.rs
- src/merkle/smt/full/error.rs
- src/merkle/smt/full/leaf.rs
- src/merkle/smt/full/proof.rs
- src/merkle/smt/mod.rs
- src/merkle/smt/simple/mod.rs
- src/merkle/smt/simple/tests.rs
- src/merkle/store/mod.rs
- src/merkle/store/tests.rs
- src/utils/mod.rs
Refactor error messages, use `thiserror` to derive errors and implement `core::error::Error`.
Various errors were renamed or restructured to provide better error messages which means this is a breaking change, so this targets `next`.
Fixes the changelog for `0.12` and moves the #343 PR to the next version, `0.13`.
Related to https://github.com/0xPolygonMiden/miden-base/issues/972.
> Refactor error messages and use `thiserror` to derive errors

- scripts/check-changelog.sh
- src/merkle/smt/mod.rs
- src/merkle/store/tests.rs
This pull request addresses minor typographical fixes in the codebase to improve clarity and maintain consistency. The changes include correcting spelling errors in comments and documentation. The modifications are straightforward and do not affect functionality.
1. **`scripts/check-changelog.sh`:**  
- Fixed typo: "explicitely" → "explicitly".
- Adjusted wording for better clarity.
2. **`src/merkle/smt/mod.rs`:**  
- Corrected spelling: "accomodate" → "accommodate".  
- Improved phrasing in comment: "when can remove" → "then can remove".
3. **`src/merkle/store/tests.rs`:**  
- Fixed typo: "the the" → "the".  
- Clarified phrasing in test description.
> fix: typos of different importance

- .github/workflows/test.yml
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- Makefile
- README.md
- src/hash/rescue/rpo/digest.rs
- src/lib.rs
- src/merkle/node.rs
- src/merkle/smt/full/mod.rs
- src/merkle/smt/full/tests.rs
- src/merkle/smt/mod.rs
- src/merkle/smt/simple/mod.rs
- src/merkle/smt/simple/tests.rs
After benchmarking of `compute_mutations` and `apply_mutations` we noticed poor performance of multiple key-value insertions into `BTreeMap` which is used in our SMT implementations. Rewriting to hashbrown's `HashMap` (which supports no-std) gave us more than 10x boost in `apply_mutations` operation for large trees.
---
apply_mutations/SimpleSmt: apply_mutations/10000
time:   [154.52 ms 163.09 ms 174.46 ms]
change: [-93.242% -92.753% -92.142%] (p = 0.00 < 0.05)
Performance has improved.
---
(More context in the PR: https://github.com/0xPolygonMiden/crypto/pull/355)
In this implementation we also introduced `smt_hashmaps` feature. If it's switched off, the SMT uses binary-tree implementation, as before. This might be useful for backward-compatibility with code, which relies on entry …
> Added support for hashmaps in `Smt` and `SimpleSmt`

- arch/arm64-sve/rpo/library.c
- arch/arm64-sve/rpo/rpo_hash_128bit.h
- arch/arm64-sve/rpo/rpo_hash_256bit.h
Graviton4 CPU reduced SVE register size from 256 to 128 bit. This PR adds support for this configuration by essentially duplicating the code. I tried doing some macro magic with variadic arguments but it ended up being more confusing than simply having 128 and 256 bit versions.
> Add SVE support for Graviton4

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/merkle/mod.rs
- src/merkle/smt/mod.rs
* Made `InnerNode` and `NodeMutation` public.
* Implemented (de)serialization of `LeafIndex`.
> Changes needed for implementing of openings computing for recent blocks

- CHANGELOG.md
- src/dsa/rpo_falcon512/signature.rs
Minor change removing a duplicated check of `h_digest==pubkey_com`at [`src/dsa/rpo_falcon512/signature.rs#L100`]( https://github.com/0xPolygonMiden/crypto/blob/2a5b8ffb2116281636a41037b8580a7d93ebb3cf/src/dsa/rpo_falcon512/signature.rs#L100), which is already done at [`src/dsa/rpo_falcon512/signature.rs#L95`]( https://github.com/0xPolygonMiden/crypto/blob/2a5b8ffb2116281636a41037b8580a7d93ebb3cf/src/dsa/rpo_falcon512/signature.rs#L95).
> remove duplicated check in falcon verification

- CHANGELOG.md
- benches/smt-subtree.rs
- src/merkle/smt/full/concurrent/mod.rs
This PR fixes #377 by ensuring that all leaves in `subtree8-rand` benchmark are unique before constructing the subtree.
Changes:
- Added a debug-only check in `build_subtree()` to detect duplicate leaf columns.
- Ensured leaves are deduplicated in `subtree8-rand` benchmark to prevent assertion failures in debug mode.
> Fix `subtree8-rand` benchmark panics with debug assertions enabled (#377)

- CHANGELOG.md
- src/merkle/smt/partial.rs
Fixes an edge case in `PartialSmt::add_path` that should result in an error but did not.
The scenario is the following: When we add an empty leaf's path to a PartialSmt as the first leaf, then the root of the partial SMT afterwards is still the empty root. This means when we add a second leaf to the SMT whose root is different, it will not result in a root conflict error.
This is because of the `self.root() != EMPTY_ROOT` exception which we use to determine whether we're adding the first leaf or not. This PR changes the way we determine whether we've added the first leaf to check for `self.0.num_leaves() != 1`, which will trigger the error also in the above case.
See `partial_smt_root_mismatch_on_empty_values` for a test that did not suceed prior to this PR.
Adds two tests checking for …
> Fix `PartialSmt` stale proofs not resulting in error

- CHANGELOG.md
- src/merkle/mmr/partial.rs
Fix panic in `PartialMmr::untrack` and add a test for it.
closes #379
> Fix panic in `PartialMmr::untrack`

- CHANGELOG.md
- src/merkle/smt/full/concurrent/mod.rs
- src/merkle/smt/full/concurrent/tests.rs
The `partial_smt_root_mismatch_on_empty_values` test passes key-value pairs to `Smt::with_entries` where some of the values are `EMPTY_WORD`. This causes a panic in the concurrent subtree computation of the `Smt` on current `next`, e.g.: https://github.com/0xPolygonMiden/crypto/actions/runs/13387187735/job/37386455081#step:4:500.
One fix is to make the test not pass empty values, which is actually unnecessary, since it's the default value. However, I think `with_entries` shouldn't panic when empty values are passed, so I fixed that instead by filtering them out early in the process.
- Tests …
> Filter empty values in `Smt::with_entries`

- src/merkle/smt/full/concurrent/mod.rs
- src/merkle/smt/full/mod.rs
- src/merkle/smt/mod.rs
- src/merkle/smt/simple/mod.rs
Trivial change to fix a warning with `--no-default-features`.
> fix: dead_code warning on pairs_to_leaf when not(feature = "concurrent")

- benches/README.md
> docs: add SMT benchmarks

- CHANGELOG.md
- src/merkle/smt/full/concurrent/mod.rs
- src/merkle/smt/full/concurrent/tests.rs
This PR optimizes duplicate key detection in `Smt::with_entries_concurrent`, reducing unnecessary overhead. The previous implementation relied on a `BTreeSet` to track seen keys, which introduced performance costs. The new approach optimistically detects duplicates within `pairs_to_leaf`, eliminating the need for additional tracking.
> smt: optimized duplicate key detection

- CHANGELOG.md
- miden-crypto/src/merkle/mmr/partial.rs
- miden-crypto/src/merkle/mmr/peaks.rs
- miden-crypto/src/merkle/mmr/tests.rs
Add default constructors to MmrPeaks and PartialMmr and unit tests.
> Add default constructors to MmrPeaks and PartialMmr

- CONTRIBUTING.md
- Cargo.toml
- LICENSE
- README.md
- miden-crypto/src/lib.rs
This PR updates outdated URLs across all Markdown files to reflect the repository renaming from `0xPolygonMiden` to `0xMiden`.  
It also updates GitHub Pages links from `0xpolygonmiden.github.io` to `0xmiden.github.io`.
> docs: update old GitHub and GitHub Pages URLs to new 0xMiden naming

- .github/workflows/test.yml
- Makefile
- miden-crypto/src/merkle/store/mod.rs
This fixes the `MerkleStore` doctest broken in #411, and enables doctests in the Makefile test targets so doctest breakages are caught by CI in the future.
Fixes #421. 
> Run doctests in CI, and fix existing broken doctest

- .github/workflows/changelog.yml
The changelog workflow has an error about the  incorrect attempt to access `inputs.changelog`, which is not available in the `pull_request` event
context. 
This change removes the invalid argument, allowing the script to use its default behavior of checking the `CHANGELOG.md` file.
> fix(ci): Correct arguments for changelog check script

- CHANGELOG.md
- miden-crypto/src/merkle/smt/partial.rs
Adds conversion from `Smt` for `PartialSmt` and serialization implementations, for completion and for https://github.com/0xMiden/miden-base/issues/1457.
> feat: Conversions, serde for PartialSmt

- miden-crypto/src/merkle/smt/partial.rs
I believe this test shouldn't exist. It's a subset of the test above and contains a typo in its name.
> Remove partial_smt_serialization_rounfdtrip test with a typo

- CHANGELOG.md
- miden-crypto/src/merkle/mmr/forest.rs
- miden-crypto/src/merkle/mmr/full.rs
This PR implements serialization for the `Mmr` struct, needed to implement serialization for `MockChain` in `miden-base` (implemented in [this PR](https://github.com/0xMiden/miden-base/pull/1642))
The end goal of these changes is to be able to serialize and deserialize the `MockRpcApi` in miden-client (explained in [this issue](https://github.com/0xMiden/miden-client/issues/1064))
> feat: implement serialization for `Mmr`

- CHANGELOG.md
- miden-crypto/src/merkle/mod.rs
- miden-crypto/src/merkle/partial_mt/mod.rs
- miden-crypto/src/merkle/partial_mt/tests.rs
- miden-crypto/src/merkle/path.rs
- miden-crypto/src/merkle/smt/simple/proof.rs
- miden-crypto/src/merkle/store/mod.rs
[Followup from #477:](https://github.com/0xMiden/crypto/pull/477#discussion_r2270774488):
> We could also rename ValuePath into MerkleProof to be consistent with the other ones - but that's for a different PR.
> Rename ValuePath to MerkleProof

- CHANGELOG.md
- miden-crypto/src/merkle/smt/full/mod.rs
- miden-crypto/src/merkle/smt/partial.rs
Expose extra getters for inner nodes, to allow to reconstruct a compressed `PartialSmt` from protobuf messages, see https://github.com/0xMiden/miden-node/pull/1158
I might be doing something wrong here, so I'd very much appreciate an alternative to the above, if such exists. I didn't find a way to access the unterlyding `InnerNode`s via `PartialSmt`.
> feat: extra getters for `InnerNode` and `NodeIndex`

- miden-crypto/benches/common/macros.rs
- miden-crypto/benches/rand.rs
Follow-up to #503 fixing one macro not using its closure properly. 🤦‍♂️
> fix: `benchmark_rand_core!` not calling `b.iter()` properly

- CHANGELOG.md
- miden-crypto/src/merkle/smt/full/leaf.rs
This small PR refactors `SmtLeaf::entries()` method to return an iterator rather than a vector.
> Make `SmtLeaf::entries()` return an iterator

- miden-crypto/src/merkle/mmr/error.rs
- miden-crypto/src/merkle/mmr/full.rs
Add a guard ensuring the requested forest does not exceed self.forest before building the Merkle path. This aligns open_at with existing validation in peaks_at and get_delta, and prevents potential out-of-bounds indexing and panics when callers pass an invalid forest.
> Validate forest in Mmr::open_at to prevent OOB access
